"""update package id - unique

Revision ID: 22100e2dbe44
Revises: 87936575d23f
Create Date: 2018-06-16 15:54:08.808360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22100e2dbe44'
down_revision = '87936575d23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'package', ['package_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package', type_='unique')
    # ### end Alembic commands ###
