"""Added name to genus, species, subspecies, and group tables

Revision ID: 25caa2024d94
Revises: 23c6ee78a2f9
Create Date: 2018-03-29 16:33:22.873305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25caa2024d94'
down_revision = '23c6ee78a2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('group', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('species', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('subspecies', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subspecies', 'name')
    op.drop_column('species', 'name')
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
