"""lineage_id optional

Revision ID: 2c14537e5a30
Revises: ecbbefaeb8ab
Create Date: 2018-11-07 12:27:40.044354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c14537e5a30'
down_revision = 'ecbbefaeb8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'lineage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'lineage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
