"""added Postgis info for packages table

Revision ID: 2e9e67222098
Revises: f89b24a27764
Create Date: 2018-03-28 15:51:13.362837

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = '2e9e67222098'
down_revision = 'f89b24a27764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('additional_gps_info', sa.String(length=1024), nullable=False))
    op.add_column('sample', sa.Column('additional_info', sa.String(length=1024), nullable=True))
    op.add_column('sample', sa.Column('coordinates', Geometry(geometry_type='POINT', srid=4326), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'coordinates')
    op.drop_column('sample', 'additional_info')
    op.drop_column('sample', 'additional_gps_info')
    # ### end Alembic commands ###
