"""added measurements as db info

Revision ID: 40e777935c4e
Revises: 61523e08f0ce
Create Date: 2018-10-12 17:49:31.819394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40e777935c4e'
down_revision = '61523e08f0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('specimen', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'specimen', 'measurement', ['measurement_id'], ['id'])
    op.drop_column('specimen', 'measurement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('measurement', postgresql.ENUM('qubit', 'nanodrop', name='measurement_enum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'specimen', type_='foreignkey')
    op.drop_column('specimen', 'measurement_id')
    op.drop_table('measurement')
    # ### end Alembic commands ###
