"""email, phone optional

Revision ID: 4d03391b7226
Revises: 2c14537e5a30
Create Date: 2018-11-08 14:09:54.283031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d03391b7226'
down_revision = '2c14537e5a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_request', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('account_request', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('partner', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('partner', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('person', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('user_account', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'N/A'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('person', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('partner', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('partner', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    op.alter_column('account_request', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    op.alter_column('account_request', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'someone@xample.org'::character varying"))
    # ### end Alembic commands ###
