"""Package, Partner, Person tables

Revision ID: 50e38d4a6181
Revises: 056acc5d6565
Create Date: 2018-03-14 16:23:52.005492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e38d4a6181'
down_revision = '056acc5d6565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
