"""package fields optional

Revision ID: 54c82a63704e
Revises: 7ad427af1233
Create Date: 2018-10-11 14:43:13.496121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54c82a63704e'
down_revision = '7ad427af1233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'courier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package', 'date_sent',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('package', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('package', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('package', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('package', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('package', 'date_sent',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('package', 'courier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
