"""initial migration

Revision ID: 56f2abfe4814
Revises: 
Create Date: 2018-06-20 20:19:40.633364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56f2abfe4814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone_code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.Column('institution', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.Column('role', postgresql.ARRAY(sa.CHAR()), server_default='{P}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=64), server_default='Role', nullable=False),
    sa.Column('description', sa.String(length=256), server_default='A description', nullable=True),
    sa.Column('can_admin', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subspecies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('authenticated', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.Column('process_location_id', sa.Integer(), nullable=False),
    sa.Column('date_sampled', sa.DateTime(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('caste', postgresql.ENUM('drone', 'worker', 'queen', name='caste_enum'), nullable=False),
    sa.Column('development_stage', postgresql.ENUM('egg', 'pupae', 'larvae', 'nymph', 'adult', name='dev_stage_enum'), nullable=False),
    sa.Column('genus_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('subspecies_id', sa.Integer(), nullable=True),
    sa.Column('lineage_id', sa.Integer(), nullable=False),
    sa.Column('origin_country', sa.Integer(), nullable=True),
    sa.Column('sender_source_id', sa.String(length=32), nullable=False),
    sa.Column('origin_locality', sa.String(length=128), nullable=True),
    sa.Column('hive', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('additional_gps_info', sa.String(length=1024), nullable=True),
    sa.Column('additional_info', sa.String(length=1024), nullable=True),
    sa.Column('freezer', sa.String(length=32), nullable=True),
    sa.Column('shelf', sa.String(length=32), nullable=True),
    sa.Column('box', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['genus_id'], ['genus.id'], ),
    sa.ForeignKeyConstraint(['lineage_id'], ['lineage.id'], ),
    sa.ForeignKeyConstraint(['origin_country'], ['country.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['process_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['subspecies_id'], ['subspecies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('collection_sample_id', sa.String(length=32), server_default='122', nullable=False),
    sa.Column('dna', sa.Float(), nullable=True),
    sa.Column('date_collected', sa.DateTime(), nullable=True),
    sa.Column('measurement', postgresql.ENUM('qubit', 'nanodrop', name='measurement_enum'), nullable=True),
    sa.Column('body_part', sa.String(length=128), nullable=True),
    sa.Column('freezer', sa.String(length=32), nullable=True),
    sa.Column('box', sa.String(length=32), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specimen')
    op.drop_table('sample')
    op.drop_table('city')
    op.drop_table('user_role')
    op.drop_table('state')
    op.drop_table('package')
    op.drop_table('user_account')
    op.drop_table('subspecies')
    op.drop_table('species')
    op.drop_table('role')
    op.drop_table('person')
    op.drop_table('partner')
    op.drop_table('location')
    op.drop_table('lineage')
    op.drop_table('genus')
    op.drop_table('courier')
    op.drop_table('country')
    op.drop_table('account_request')
    # ### end Alembic commands ###
