"""added nr of specimens in received vial field

Revision ID: 61523e08f0ce
Revises: b8bb40a0cd6e
Create Date: 2018-10-12 15:22:30.853110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61523e08f0ce'
down_revision = 'b8bb40a0cd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('specimens_in_received_vial', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'specimens_in_received_vial')
    # ### end Alembic commands ###
