"""fix city tables

Revision ID: 6cdd423686fa
Revises: e85fd112c609
Create Date: 2018-05-08 11:05:34.862763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdd423686fa'
down_revision = 'e85fd112c609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_state_id_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_state_id_fkey', 'city', 'country', ['state_id'], ['id'])
    # ### end Alembic commands ###
