"""changed sample and specimen model to reflect new requirements

Revision ID: 7ad427af1233
Revises: 56f2abfe4814
Create Date: 2018-09-20 12:12:56.267706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ad427af1233'
down_revision = '56f2abfe4814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'role',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('sample', 'subspecies_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sample', 'box')
    op.drop_column('sample', 'freezer')
    op.drop_column('sample', 'shelf')
    op.add_column('specimen', sa.Column('dna_box', sa.String(length=32), nullable=True))
    op.add_column('specimen', sa.Column('dna_freezer', sa.String(length=32), nullable=True))
    op.add_column('specimen', sa.Column('specimen_box', sa.String(length=32), server_default='A', nullable=False))
    op.add_column('specimen', sa.Column('specimen_freezer', sa.String(length=32), server_default='A', nullable=False))
    op.drop_column('specimen', 'box')
    op.drop_column('specimen', 'freezer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('freezer', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('specimen', sa.Column('box', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('specimen', 'specimen_freezer')
    op.drop_column('specimen', 'specimen_box')
    op.drop_column('specimen', 'dna_freezer')
    op.drop_column('specimen', 'dna_box')
    op.add_column('sample', sa.Column('shelf', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('freezer', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('box', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.alter_column('sample', 'subspecies_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'role',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###
