"""user table

Revision ID: 88f55873e8bb
Revises: e9738549d0c9
Create Date: 2018-03-12 16:21:50.478575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f55873e8bb'
down_revision = 'e9738549d0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.String(length=50), nullable=False, server_default='fname'))
    op.add_column('user', sa.Column('lname', sa.String(length=50), nullable=False, server_default='lname'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###
