"""User inherit from Person abstract class

Revision ID: 8cc8e7451a8a
Revises: 4d80b4b5ceab
Create Date: 2018-03-14 17:45:29.662579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc8e7451a8a'
down_revision = '4d80b4b5ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_request', sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('account_request', 'phone')
    # ### end Alembic commands ###
