"""added active field in Base model

Revision ID: a0b7884395f7
Revises: b7517cefa54d
Create Date: 2018-04-30 11:06:24.011599

"""
from alembic import op
import sqlalchemy as sa

import app.mod_util.utils
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'a0b7884395f7'
down_revision = 'b7517cefa54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_request', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('courier', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('genus', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('lineage', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('location', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('package', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('partner', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('person', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('role', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('sample', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('species', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('specimen', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('subspecies', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('user_account', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('user_role', sa.Column('active', sa.Boolean(), server_default='t', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'active')
    op.drop_column('user_account', 'active')
    op.drop_column('subspecies', 'active')
    op.drop_column('specimen', 'active')
    op.drop_column('species', 'active')
    op.drop_column('sample', 'active')
    op.drop_column('role', 'active')
    op.drop_column('person', 'active')
    op.drop_column('partner', 'active')
    op.drop_column('package', 'active')
    op.drop_column('location', 'active')
    op.drop_column('lineage', 'active')
    op.drop_column('genus', 'active')
    op.drop_column('courier', 'active')
    op.drop_column('account_request', 'active')
    # ### end Alembic commands ###
