"""removed PackageIndex table

Revision ID: a18fbc953082
Revises: 22100e2dbe44
Create Date: 2018-06-16 16:00:11.038850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18fbc953082'
down_revision = '22100e2dbe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_index',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('next_suffix', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='package_index_pkey')
    )
    # ### end Alembic commands ###
