"""change email to unique in AccountRequest

Revision ID: a76bdcdafccb
Revises: d31013b0daf6
Create Date: 2018-03-13 11:52:16.268127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76bdcdafccb'
down_revision = 'd31013b0daf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account_request', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_request', type_='unique')
    # ### end Alembic commands ###
