"""update

Revision ID: b7517cefa54d
Revises: a38220bf44b2
Create Date: 2018-04-18 11:21:36.453500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.mod_util.utils
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'b7517cefa54d'
down_revision = 'a38220bf44b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lineage_id', app.mod_util.utils.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('specimen_group_id_fkey', 'specimen', type_='foreignkey')
    op.drop_table('group')
    op.add_column('genus', sa.Column('genus_id', app.mod_util.utils.GUID(), nullable=False))
    op.add_column('genus', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('partner', sa.Column('institution', sa.String(length=256), nullable=True))
    op.drop_column('partner', '_Partner__institution')
    op.drop_index('idx_sample_coordinates', table_name='sample')
    op.drop_column('sample', 'sample_quality')
    op.add_column('species', sa.Column('species_id', app.mod_util.utils.GUID(), nullable=False))
    op.add_column('specimen', sa.Column('lineage_id', sa.Integer(), nullable=False))
    #op.drop_constraint('specimen_group_id_fkey', 'specimen', type_='foreignkey')
    op.create_foreign_key(None, 'specimen', 'lineage', ['lineage_id'], ['id'])
    op.drop_column('specimen', 'group_id')
    op.add_column('subspecies', sa.Column('subspecies_id', app.mod_util.utils.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subspecies', 'subspecies_id')
    op.add_column('specimen', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specimen', type_='foreignkey')
    op.create_foreign_key('specimen_group_id_fkey', 'specimen', 'group', ['group_id'], ['id'])
    op.drop_column('specimen', 'lineage_id')
    op.drop_column('species', 'species_id')
    op.add_column('sample', sa.Column('sample_quality', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index('idx_sample_coordinates', 'sample', ['coordinates'], unique=False)
    op.add_column('partner', sa.Column('_Partner__institution', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('partner', 'institution')
    op.drop_column('genus', 'name')
    op.drop_column('genus', 'genus_id')
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='group_pkey')
    )
    op.drop_table('lineage')
    # ### end Alembic commands ###
