"""added Stage and Caste as tables

Revision ID: b8bb40a0cd6e
Revises: 4e8b906db876
Create Date: 2018-10-11 16:44:45.174125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8bb40a0cd6e'
down_revision = '4e8b906db876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('caste_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('sample', sa.Column('development_stage_id', sa.Integer(), server_default='4', nullable=False))
    op.create_foreign_key(None, 'sample', 'stage', ['development_stage_id'], ['id'])
    op.create_foreign_key(None, 'sample', 'caste', ['caste_id'], ['id'])
    op.drop_column('sample', 'caste')
    op.drop_column('sample', 'development_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('development_stage', postgresql.ENUM('egg', 'pupae', 'larvae', 'nymph', 'adult', name='dev_stage_enum'), autoincrement=False, nullable=False))
    op.add_column('sample', sa.Column('caste', postgresql.ENUM('drone', 'worker', 'queen', name='caste_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'development_stage_id')
    op.drop_column('sample', 'caste_id')
    # ### end Alembic commands ###
