"""update sample and specimen fields

Revision ID: d4fd58a9f0a7
Revises: 94f38d2766ce
Create Date: 2018-05-08 10:29:54.429957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fd58a9f0a7'
down_revision = '94f38d2766ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'collection_sample_id')
    op.add_column('specimen', sa.Column('collection_sample_id', sa.String(length=32), nullable=False, default='122', server_default='122'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen', 'collection_sample_id')
    op.add_column('sample', sa.Column('collection_sample_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
