"""user table

Revision ID: e9738549d0c9
Revises: a424985fc6fe
Create Date: 2018-03-09 10:08:16.398776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9738549d0c9'
down_revision = 'a424985fc6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'authenticated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'authenticated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
