"""initial tables for sample, specimen

Revision ID: f89b24a27764
Revises: 8cc8e7451a8a
Create Date: 2018-03-28 15:13:11.518062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89b24a27764'
down_revision = '8cc8e7451a8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
### manually added GUID helper
from app.mod_util.utils import GUID
sa.GUID = GUID

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('fname', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('lname', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('phone', sa.String(length=128), server_default='N/A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.Column('process_location_id', sa.Integer(), nullable=False),
    sa.Column('date_sampled', sa.DateTime(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('sample_quality', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('origin_country', sa.String(length=128), nullable=False),
    sa.Column('origin_state', sa.String(length=128), nullable=False),
    sa.Column('origin_city', sa.String(length=128), nullable=False),
    sa.Column('origin_locality', sa.String(length=128), nullable=True),
    sa.Column('hive', sa.String(length=64), nullable=True),
    sa.Column('freezer', sa.String(length=32), nullable=False),
    sa.Column('shelf', sa.String(length=32), nullable=False),
    sa.Column('box', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['process_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('package', sa.Column('courier_id', sa.Integer(), nullable=False))
    op.add_column('package', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('package', sa.Column('package_id', sa.GUID(), nullable=False))
    op.add_column('package', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('package', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('package', sa.Column('tracking_number', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'package', 'person', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'package', 'courier', ['courier_id'], ['id'])
    op.create_foreign_key(None, 'package', 'location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'package', 'person', ['receiver_id'], ['id'])
    op.drop_column('package', 'carrier')
    op.drop_column('package', 'process_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('process_location', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('package', sa.Column('carrier', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_column('package', 'tracking_number')
    op.drop_column('package', 'sender_id')
    op.drop_column('package', 'receiver_id')
    op.drop_column('package', 'package_id')
    op.drop_column('package', 'location_id')
    op.drop_column('package', 'courier_id')
    op.drop_table('specimen')
    op.drop_table('sample')
    op.drop_table('person')
    op.drop_table('location')
    op.drop_table('courier')
    # ### end Alembic commands ###
