"""fields upgraded definition

Revision ID: fc4ce98c74b4
Revises: 9a308c717b3e
Create Date: 2018-06-15 17:18:38.622642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc4ce98c74b4'
down_revision = '9a308c717b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    measurement_enum = postgresql.ENUM('qubit', 'nanodrop', name='measurement_enum')
    measurement_enum.create(op.get_bind())
    op.drop_index('idx_sample_coordinates', table_name='sample')
    op.drop_column('sample', 'sample_id')
    op.add_column('specimen', sa.Column('body_part', sa.String(length=128), nullable=True))
    op.add_column('specimen', sa.Column('box', sa.String(length=32), nullable=True))
    op.add_column('specimen', sa.Column('date_collected', sa.DateTime(), nullable=False))
    op.add_column('specimen', sa.Column('dna', sa.Float(), nullable=True))
    op.add_column('specimen', sa.Column('freezer', sa.String(length=32), nullable=True))
    op.add_column('specimen', sa.Column('measurement', postgresql.ENUM('qubit', 'nanodrop', name='measurement_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen', 'measurement')
    op.drop_column('specimen', 'freezer')
    op.drop_column('specimen', 'dna')
    op.drop_column('specimen', 'date_collected')
    op.drop_column('specimen', 'box')
    op.drop_column('specimen', 'body_part')
    op.add_column('sample', sa.Column('sample_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index('idx_sample_coordinates', 'sample', ['coordinates'], unique=False)

    measurement_enum = postgresql.ENUM('qubit', 'nanodrop', name='measurement_enum')
    measurement_enum.create(op.get_bind())
    # ### end Alembic commands ###
